Fliplet/fliplet-widget-file-manager

js/interface.js
Also fix folder selection. Before, once you select a folder it was
always sending a folder id.
=> Assign files to apps

css/interface.css, interface.html, js/interface.js, widget.json
See issue for list of enhancements: https://github.com/Fliplet/fliplet-studio/issues/864
=> High & Medium Priorities - #864

css/interface.css, interface.html, js/interface.js
=> Zipping files and folders

css/interface.css, interface.html, js/interface.js, widget.json
https://cl.ly/00393k463I1N
https://cl.ly/2Q3V2S3T3R1a
=> Drag and Drop Upload

css/interface.css, js/interface.js
- Allow the File Manager to be opened in a specific folder
=> Allow to open in an app folder

js/interface.js
Does not load the organisation folder if intended to open in a specific folder
=> Loading tweaks

css/interface.css, interface.html, js/interface.js
- ID column added for quick visibility of the folder/files's ID
=> Folder / File ID added

js/interface.js
=> Single click will select but not multi select

css/interface.css
Ref. https://github.com/Fliplet/fliplet-studio/issues/2976
=> Fixes issues where icons of folder or file are shifted down in File Manager

js/interface.js
Ref. https://github.com/Fliplet/fliplet-e2e-tests/issues/95
=> Ensures content from one folder isn't loaded when user is browsing another folder

js/interface.js
requires https://github.com/Fliplet/fliplet-api/pull/3206
=> use CDN when previewing files

interface.html, js/interface.js
basically reverts my old work :(
=> don't use cdn when previewing files

css/interface.css
Ref. https://github.com/Fliplet/fliplet-studio/issues/4363
=> Break long app names to separate lines

css/interface.css
Ref. https://github.com/Fliplet/fliplet-studio/issues/4363
=> Updated fix for FF, IE 11 and Edge

css/interface.css
Reverts Fliplet/fliplet-widget-file-manager#37
=> Revert "Selectall checkbox bug"

css/interface.css, interface.html, js/interface.js
@squallstar 
Includes fixes:
1) Add visual feedback for loading states for any loading 
2) After clearing a search, sometimes it ends up with this view ( suppose it's searching for all files instead of returning to display the folder I was looking at?)
3) The path becomes unreadable when I select a row (change link text color to white)
No ref to the Github issue
=> Fixes for Search task

css/interface.css, interface.html, js/interface.js
@squallstar 
Scrolling causes weird behaviors
The problem was with absolute positioning, side blocks do not take into account the size of the middle block. 
No ref to the Github issue
=> Scrolling causes weird behaviors

css/interface.css, interface.html, js/interface.js, widget.json
=> Drag and drop 864

css/interface.css, js/interface.js
@squallstar 
1) Fixed file long name issue
2) Highlight active drop area
3) Removed space between checkbox and name
4) Fixed issue when no show the select all checkbox after the search
No ref to the Github issue
=> Fixed name and drop styles

css/interface.css, js/interface.js
@squallstar 
Fixed the drop area highlight after cancel moving
No ref to the Github issue
=> Fixed drop area highlight

css/interface.css, interface.html
@tonytlwu @squallstar 
https://github.com/Fliplet/fliplet-studio/issues/4644
Changed 'clean' div to times icon
=> Changed clean div to times icon

js/interface.js
@tonytlwu @squallstar 
We could not drag and drop files in the root folder(organization) from desktop because in the request no organization id.
ref https://github.com/Fliplet/fliplet-studio/issues/4794
video: https://cl.ly/fac23591b9df
=> Drag drop 4794

js/interface.js
ref https://github.com/Fliplet/fliplet-studio/issues/5425
=> disable folder upload

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5029
Allow users to search for files by ID
This change will not cause an issue with the search if back end changes haven't been made.
=> Allow users to search for files by ID

js/interface.js
https://github.com/Fliplet/fliplet-studio/issues/5642
Updated default modal window to Fliplet modal.
=> Updated modal 

js/interface.js
for https://github.com/Fliplet/fliplet-api/pull/4221
=> [Fix] authenticate thumbnails

css/interface.css, interface.html, js/interface.js, widget.json
OD-67 - https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-67
OD-66 - https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-66
Created trash view and restore delete functionality for file manager
https://screencast-o-matic.com/watch/cYQZ2kd08D
@upplabs-alex-levchenko
=> OD-66/67 [Feature] Create trash view and functionality for file manager

interface.html
OD-231 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-231
Change need help link
https://screencast-o-matic.com/watch/cYXQImMTk5
@YaroslavOvdii @upplabs-alex-levchenko
=> OD-231 [Fix] It is not possible to add a new file or create a new folder in File manger

interface.html, js/interface.js
OD-187 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-187
Added if condition
@YaroslavOvdii @upplabs-alex-levchenko
=> OD-187 [Fix] Change need help link

interface.html, js/interface.js, widget.json
OD-117 https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-117
- Fix with empty names of files.
- Added new pop-up with a new scenario.
https://screencast-o-matic.com/watch/crVTQP9J5Y
@upplabs-alex-levchenko @ivandevupp
=> OD-117 [Fix] Impossible to restore a file from a deleted folder in File Manager Trash

interface.html, js/interface.js
@sofiiakvasnevska
OD-113 https://weboo.atlassian.net/browse/OD-113
'Go to Folder' button redirects now to needed location
https://monosnap.com/file/sFqKpqUILN91U9vUXVXJVmQuMpzZYX
@upplabs-alex-levchenko @AndrRyaz
=> OD-113 [Fix] GoTo Folder button redirects now to needed location

js/interface.js
@sofiiakvasnevska
OD-111 https://weboo.atlassian.net/browse/OD-111
Grammatical number message correct spelling for delete forever action
https://monosnap.com/file/PGnQclpDohB5To3ikcWmmF9xlnDR3V
@upplabs-alex-levchenko @AndrRyaz
=> OD-111 [Task] Grammatical number message correct spelling for delete forever action

js/interface.js
@sofiiakvasnevska
OD-342 https://weboo.atlassian.net/browse/OD-342
Generate correct modal delete message for multiple or single folders and files.
https://monosnap.com/file/EpwPP1DzPEA24B3JD1HHPRlrkFpINy
@upplabs-alex-levchenko @YaroslavOvdii
=> OD-342 [Fix] Generate correct modal delete message for multiple or single folders and files

interface.html, js/interface.js
https://weboo.atlassian.net/browse/OD-113
We have created new functions that are controlling user redirection in the file manager. For the basis of these functions was taken from the callbacks that were used on click and dblclick events in the file manager.
https://share.getcloudapp.com/RBu40oyE
@upplabs-alex-levchenko @ivandevupp
=> OD-113 [Fix] User will be redirected to the currect folder when restore file and press 'Go to folder' button

js/interface.js
https://weboo.atlassian.net/browse/OD-113
Setting the correct organization ID.
https://share.getcloudapp.com/o0uEQQjz
@upplabs-alex-levchenko @ivandevupp
=> OD-113 [Fix] When users will restore folders within a folder in the organization root they will be redirected correctly

interface.html
OD-180 https://weboo.atlassian.net/browse/OD-180
Rename Delete button in data source manager
@upplabs-alex-levchenko @ivandevupp @YaroslavOvdii
=> OD-180 [Feature] Change the name of 'Delete' button

css/interface.css, interface.html, js/interface.js
OD-150 https://weboo.atlassian.net/browse/OD-150
Added new column for trash in file manager
http://somup.com/crfUIpFvnj
@upplabs-alex-levchenko @ivandevupp @YaroslavOvdii
=> OD-150 [Feature] Added a new column showing where the item was before deletion 

js/interface.js
@sofiiakvasnevska
OD-498 https://weboo.atlassian.net/browse/OD-498
Remove the "NEW" button when going to Trash holder
http://somup.com/cr1e6nqZUz
@upplabs-alex-levchenko @YaroslavOvdii
=> OD-498[Fix] remove  the "NEW" button from Trash

js/interface.js
Please review by ignoring white space changes.
=> ID-1105 [Fix] Ensure users can navigate to newly created folders

.eslintrc, .gitignore, interface.html, js/interface.js, package-lock.json, package.json
Ref. https://weboo.atlassian.net/browse/ID-1270
Also adds [lazy loading](https://www.w3schools.com/tags/att_img_loading.asp) to the file and app thumbnails.
=> ID-1270 [Feat] Report file upload errors to the user

js/interface.js, package-lock.json, package.json
@romanyosyfiv
OD-702 https://weboo.atlassian.net/browse/OD-702
**Problem**: The alert closure function was not implemented
**Solution**: Added setTimeout function to close the alert
@upplabs-alex-levchenko
=> OD-702 [Fix] Tweaks UX of alerts when moving files & folders

css/interface.css, interface.html, js/interface.js
@romanyosyfiv @inna-bieshulia
OD-701 https://weboo.atlassian.net/browse/OD-701
**Problem:** The function of correct display of columns was added only when the modal window was loaded.
**Solution:** Showing the correct columns is added when updating the list and when moving the last file to the trash.
https://storyxpress.co/video/kywtuqcusq4d5xxbl
@upplabs-alex-levchenko
=> OD-701 [Fix] Fixed display of file manager and trash folder columns

js/interface.js
FIle-manager
This PR will update the progress bar for storage after deleteing the file/folder
[XOR-155](https://weboo.atlassian.net/browse/XOR-155)
https://user-images.githubusercontent.com/101858104/171556958-451f9f51-aa70-4ea3-8e61-f99ae6ee4d4d.mp4
None
None
None
=> XOR-155 [FIX]  Ensure the progress bar for storage refreshed after deleteing the file/folder

interface.html, js/interface.js
File manager
- fixed resolving paths of search results done within an organization;
- added app name in organization search results path string;
- added app name into breadcrumbs;
https://github.com/Fliplet/fliplet-api/pull/6076
https://weboo.atlassian.net/browse/ID-4064
=> ID-4064 [fix] navigation to organization search results; app in breadcrumbs and pathways

interface.html, js/interface.js
Reverts Fliplet/fliplet-widget-file-manager#104
due to QA failed
=> Revert "ID-4064 [fix] navigation to organization search results; app in breadcrumbs and pathways"

js/interface.js, package-lock.json, package.json
This PR:
- ensures that search type select options are updated with breadcrumbs;
- includes refactor of generating breadcrumbs with newer syntax and better readability;
- bumps eslint-config-fliplet to 1.0.12
https://weboo.atlassian.net/browse/ID-4065
=> ID-4065 [fix] in-app file manager global search

js/interface.js, package-lock.json, package.json
This reverts commit f256f9e80e69641092fe017dc40a0f5c7eaf976b.
=> Revert "ID-4065 [fix] in-app file manager global search (#113)"

js/interface.js
https://weboo.atlassian.net/browse/ID-4265
=> fix(ID-4265): removed download button from trash folder items

js/interface.js
https://weboo.atlassian.net/browse/PR-43
https://weboo.atlassian.net/browse/PR-42
=> fix(PR-42/PR-43): prevent using empty name when creating folder or renaming file or folder

js/interface.js, package-lock.json, package.json
https://weboo.atlassian.net/browse/PS-123
=> PS-123 [fix] in-app file manager global search

interface.html, js/interface.js
**Product areas affected**
Fliplet File Manager
**What does this PR do?**
Displays the file size with appropriate units e.g KB, MB, etc., in the file manager table where file size metadata is available.
**JIRA ticket**
[PS-956](https://weboo.atlassian.net/browse/PS-956)
[PS-956]: https://weboo.atlassian.net/browse/PS-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-956 [FEAT] add file size column to file manager table

js/interface.js, package-lock.json, package.json
Reverts Fliplet/fliplet-widget-file-manager#122 due to QA fail.
=> Revert "PS-123 [fix] in-app file manager global search"
